name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SubhobrataMaity
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 